spring:
  profiles:
    active: local
  datasource:
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: creditHikariCP
      max-lifetime: 60000
      connection-timeout: 30000
      connection-test-query: SELECT 1
      login-timeout: 5
      validation-timeout: 30000
    url: jdbc:mysql://${dbhost}/test?serverTimezone=Asia/Shanghai&autoReconnect=true&autoReconnectForPools=true&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${dbuser}
    password: ${dbpw}
mybatis:
  mapper-locations: classpath*:/mapper/*.xml

---
spring:
  profiles: dev
dbhost: sh-cdb-fhama989.sql.tencentcdb.com:63156
dbuser: root
dbpw: jHnXk31UXZasddf
---
spring:
  profiles: local
dbhost: sh-cdb-fhama989.sql.tencentcdb.com:63156
dbuser: root
dbpw: jHnXk31UXZasddf